name: PHP8.3

on:
  push:
    branches: [ master, beta, dev ]
  pull_request:
    branches: [ master, beta, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@8.4
        with:
          dir: '.'
      - name: Run ESLint
        run: npm run lint
