name: Build

on:
  push:
    branches: [ beta, dev ]
  pull_request:
    branches: [ beta, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 17.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@8.2
        with:
          dir: '.'
      - name: eslint
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: resources/
